---
baseURL:                "/"
languageCode:           "en-us"
title:                  "Joshua M. Agbeku"
disableLiveReload:      true
watch:                  true
preservetaxonomynames:  true

params:
  description:   "Full stack Web developer based in Accra,Ghana"
  author:        "Agbeku M. Joshua"
  title_first:   "Joshua"
  title_last:    "Agbeku"
  no_index:      true

menu:
  main:
    - name:        "home"
      identifier:  "home"
      url:         "/"
      weight:      1
    - name:        "projects"
      identifier:  "projects"
      url:         "/projects"
      weight:      2
    - name:        "cv"
      identifier:  "cv"
      url:         "/cv"
      weight:      3
    - name:        "about"
      identifier:  "about"
      url:         "/about"
      weight:      4
    - name:        "Blog"
      identifier:  "blog"
      url:         "/blog"
      weight:      5
    - name:        "hire me"
      identifier:  "hire-me"
      url:         "/hire-me"
      weight:      6

taxonomies:
  language:       "Languages"
  framework:      "Frameworks"
  infrastructure: "Infrastructure"
  tool:           "Tools"
  category:       "Categories"
...

